esteem_admin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('studentsms.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
]

studentsms/urls.py
from django.urls import path
from . import views

app_name = 'studentsms'

urlpatterns = [
   
    path('', views.index, name = 'index'),
    path('myview', views.myview, name = 'myview'),
    path('add', views.add_students, name = 'add'),
    path('update/<pk>/', views.update_students, name = 'update'),
    path('delete/<pk>/', views.delete_students, name = 'delete'),
    path('pdf_all', views.pdf_all_view, name = 'pdf_all'),
    path('pdf_id/<int:pk>/', views.pdf_id_view, name = 'pdf_id'),
]

studentsms/models.py
from django.db import models
from django import forms

# Create your models here.

class students_reg(models.Model):
    class_chice = [
        ('JSS1','JSS1'),
        ('JSS2','JSS2'),
        ('JSS3','JSS3'),
        ('SS1','SS1'),
        ('SS2','SS2'),
        ('SS3','SS3'),
        ]
    sex_chice = [
        ('male','male'),
        ('female','female'),
        ]
    status_chice = [
        ('active','active'),
        ('inactive','inactive'),
        ]
    house_choice = [
        ('red','red'),
        ('blue','blue'),
        ('yellow','yellow'),
        ('green','green'),
        ]

    names = models.CharField(
        max_length= 225, null = True, blank =True)
    dob = models.DateField(
        null = True, blank =True )
    sex = models.CharField(
        choices = sex_chice,
        max_length= 225, null = True, blank =True)
    level = models.CharField(choices = class_chice,
    max_length= 225,null = True, blank =True)
    admin_no = models.CharField(
        unique=True,
        max_length= 225, null = True, blank =True)
    house = models.CharField(
        choices= house_choice,
        max_length= 225, null = True, blank =True)
    address = models.CharField(
        max_length= 555, null = True, blank =True)
    status = models.CharField(
        choices = status_chice,
        max_length= 555, null = True, blank =True)    
    father_no = models.CharField(
        max_length= 225, null = True, blank =True)
    father_email = models.CharField(
        max_length= 225, null = True, blank =True)
    mother_no = models.CharField(
        max_length= 225, null = True, blank =True)
    mother_email = models.CharField(
        max_length= 225, null = True, blank =True)
    created_date = models.DateTimeField(
    auto_now_add = True,
    null = True, blank =True)

    def __str__(self):
        return f'{self.names}'

studentsms/forms.py
from studentsms.models import students_reg 
from django import forms
from django.forms import ModelForm
from django.db import models

class studentsform(forms.ModelForm):
    class Meta:
        model= students_reg
        fields= '__all__'
        # widgets ={
        #     'names':forms.TextInput(attrs={'class':'input'})
        # }

studentsms/views.py
from django.shortcuts import render, HttpResponse,redirect, get_list_or_404
from studentsms.models import students_reg
from studentsms.forms import studentsform
from studentsms.filters import StudentsFilter
from django.contrib.auth.decorators import login_required
from django.conf import settings

# Create your views here.
@login_required(login_url ='/accounts/login/')
def index(request):
   
    posts = students_reg.objects.order_by('-created_date')
    jss1 = students_reg.objects.filter(level__exact='JSS1').count()
    jss2 = students_reg.objects.filter(level__exact='JSS2').count()
    jss3 = students_reg.objects.filter(level__exact='JSS3').count()
    ss1 = students_reg.objects.filter(level__exact='SS1').count()
    ss2 = students_reg.objects.filter(level__exact='SS2').count()
    ss3 = students_reg.objects.filter(level__exact='SS3').count()
    myfilter = StudentsFilter(request.GET, queryset= posts)
    posts=myfilter.qs
    counter = posts.count()
    context = {
        'posts':posts,
        'counter':counter,
        'jss1':jss1,
        'jss2':jss2,
        'jss3':jss3,
        'ss1':ss1,
        'ss2':ss2,
        'ss3':ss3,
        'myfilter':myfilter
    }
    return render(request, 'studentsms/index.html', context)

# add records
def add_students(request):
    if request.method == 'POST':
        form = studentsform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('studentsms:add')
    
    form = studentsform()
    context= {
         'form':form
     }
    return render(request, 'studentsms/add.html', context)


def update_students(request,pk):
    id = students_reg.objects.get(pk=pk)
    form = studentsform(instance = id)
    if request.method == 'POST':
        form = studentsform(request.POST, instance = id)
        if form.is_valid():
            form.save()
            return redirect('studentsms:index')
    
    #form = studentsform()
    context= {
         'form':form
     }
    return render(request, 'studentsms/update.html', context)

def delete_students(request,pk):
    item = students_reg.objects.get(pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('studentsms:index')

    context= {
         'item':item
     }
    return render(request, 'studentsms/delete.html', context)

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders

def myview(request):
    posts = students_reg.objects.order_by('-created_date')
    context={
        'posts':posts
    }
    template_path = 'studentsms/pdf_filter.html'
    context = {'myvar': posts}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

# download pdf all view
def pdf_all_view(request):
    posts = students_reg.objects.order_by('-created_date')
    counter = posts.count()
    myfilter = StudentsFilter(request.GET, queryset= posts)
    template_path = 'studentsms/pdf_all.html'
    context = {
        'posts':posts,
        'counter':counter,
        'myfilter':myfilter
        }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = ' filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

# download pdf id view
def pdf_id_view(request, *args, **kwarks):
    post = students_reg.objects.order_by('-created_date')
    pk = kwarks.get('pk')
    posts = get_list_or_404(students_reg, pk= pk)
    
    counter = post.count()
    template_path = 'studentsms/pdf_id.html'
    context = {
        'posts': posts,
        'counter':counter
        }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = ' filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

studentsms/templates/studentsms/add.html
{% extends 'studentsms/base.html'%}
{% load widget_tweaks %}

{% block title %} 
<h1>Add posts</h1>
{% endblock %}

{% block body %} 

<div class="card-header bg-success text-white" >
<form class="" action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}

<p>{% render_field form.names.label %}</p>
<p>{% render_field form.names autofocus=True class="form-control" placeholder='Add Names Here' %}</p>
<p>{% render_field form.dob.label %}</p>
<p>{% render_field form.dob autofocus=True class="form-control" placeholder='Add date of birth Here' %}</p>
<p>{% render_field form.sex.label %}</p>
<p>{% render_field form.sex autofocus=True class="form-control" placeholder='Add sex Here' %}</p>
<p>{% render_field form.level.label %}</p>
<p>{% render_field form.level autofocus=True class="form-control" placeholder='Add class Here' %}</p>
<p>{% render_field form.admin_no.label %}</p>
<p>{% render_field form.admin_no autofocus=True class="form-control" placeholder='Add admin no Here' %}</p>
<p>{% render_field form.house.label %}</p>
<p>{% render_field form.house autofocus=True class="form-control" placeholder='Add house Here' %}</p>
<p>{% render_field form.address.label %}</p>
<p>{% render_field form.address autofocus=True class="form-control" placeholder='Add address Here' %}</p>
<p>{% render_field form.status.label %}</p>
<p>{% render_field form.status autofocus=True  class="form-control" placeholder='Add status Here' %}</p>
<p>{% render_field form.father_no.label %}</p>
<p>{% render_field form.father_no autofocus=True class="form-control" placeholder='Add father phone number Here' %}</p>
<p>{% render_field form.mother_no.label %}</p>
<p>{% render_field form.mother_no autofocus=True class="form-control" placeholder='Add mother phone number Here' %}</p>
<p>{% render_field form.father_email.label %}</p>
<p>{% render_field form.father_email autofocus=True class="form-control" placeholder='Add father email Here' %}</p>
<p>{% render_field form.mother_email.label %}</p>
<p>{% render_field form.mother_email autofocus=True class="form-control" placeholder='Add mother email Here' %}</p>
<br>
<button class="w-50 btn btn-dark ">Add Students</button>
</form>
</div>

{% endblock %}

studentsms/templates/studentsms/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% block body %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

studentsms/templates/studentsms/delete.html
{% extends 'studentsms/base.html' %}

{% load widget_tweaks %}

{% block title %}
<title>delete page</title>
{% endblock %}

{% block body %}
<style>
    .t{
        padding: 30px;
    }
</style>
<h1 class="t text-danger">Are you sure you want to delete {{item}}'s records?</h1>

<div class="card-header h-50 bg-success text-white" >
<form class="form-control" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

   <button type="submit" class="btn  btn-primary">confirm</button>
   <hr>
   <button class="btn  btn-primary"><a class="text-white" href="{% url 'studentsms:index' %}">concel</a></button>
</form>

</div>
{% endblock %}

studentsms/templates/studentsms/index.html
{% extends 'studentsms/base.html' %}
{% load mathfilters %}
{% load widget_tweaks %}
{% block title %} Index Page {% endblock %}

{% block body %}
<style>
    body{
        width: 100%;
        font-family: 'Times New Roman', Times, serif;
    }
    .menu{
        color: white;
       
    }
    .re{
        display: flex;
        justify-content: center;
        flex-wrap: wrap;  
    }
    .re>*{
        flex: 1 1 auto;
        margin: 5px;
        border: 2px dotted black;
    }
    .table1{
        /* width: 100%; */
         margin: 0 auto 0 auto;
         box-shadow: 5px 12px 5px black;
         border: 2px dotted black;
    }
    tr:hover{
        background-color: blanchedalmond;
    }
    .welcome{
        padding: 10px;
        width: 100%;
    }
    th{
        padding: 10px;
    }

</style>
<div class = 'welcome bg-success text-white'>
<h4>Hello, {{user.username}} welcome to Admin</h4>
<a class="text-white " href="{% url 'studentsms:add' %}">Add Student</a><br>
<a  class="text-white " href="{% url 'studentsms:pdf_all' %}">Download all Records</a>

</div>

<div class="re text-white">
    
        <div class="bg-success card-header">Total Students: {{counter}}</div>
        <div class="bg-success card-header">JSS1: {{jss1}} | {{jss1|div:counter|mul:100|floatformat}}% </div>
        <div class="bg-success card-header">JSS2: {{jss2}} | {{jss2|div:counter|mul:100|floatformat}}% </div>
        <div class="bg-success card-header">JSS3: {{jss3}} | {{jss3|div:counter|mul:100|floatformat}}% </div>
        <div class="bg-success card-header">SS1: {{ss1}} | {{ss1|div:counter|mul:100|floatformat}}% </div>
        <div class="bg-success card-header">SS2: {{ss2}} | {{ss2|div:counter|mul:100|floatformat}}% </div>
        <div class="bg-success card-header">SS3: {{ss3}} | {{ss3|div:counter|mul:100|floatformat}}% </div>
        <!-- <div class="bg-success card-header">ff{{t|div:counter|mul:100}}</div> -->
              
</div>

<hr>
<div class="container card-header text-center">
<form class="" action="" method="GET" enctype="multipart/form-data">
{% csrf_token %}

{{myfilter.form.label_tag}}
<p>{{myfilter.form}}</p>

<button type="submit" class="btn btn-dark">search</button>
<!-- <button type="reset" class="btn  btn-dark">refresh</button> -->
</form>
</div>
<hr>
<table style="margin-top: 50px;" class=" table1 table-responsive table-bordered">
    <thead>
      <tr>
        <th scope="col">names</th>
        <th scope="col">class</th>
        <th scope="col">dob</th>
        <th scope="col">sex</th>
        <th scope="col">admin_no</th>
        <th scope="col">address</th>
        <th scope="col">house</th>
        <th scope="col">status</th>
        <th scope="col">f-no</th>
        <th scope="col">f-email</th>
        <th scope="col">m-no</th>
        <th scope="col">m-email</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
        <th scope="col">Download</th>
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr>
        <td>{{post.names}}</td>
        <td>{{post.level}}</td>
        <td>{{post.dob}}</td>
        <td>{{post.sex}}</td>
        <td>{{post.admin_no}}</td>
        <td>{{post.address}}</td>
        <td>{{post.house}}</td>
        <td>{{post.status}}</td>
        <td>{{post.father_no}}</td>
        <td>{{post.father_email|urlize}}</td>
        <td>{{post.mother_no}}</td>
        <td>{{post.mother_email|urlize}}</td>
        <td><a href="{% url 'studentsms:update' post.pk %}">Edit</a></td>
        <td><a class="text-danger" href="{% url 'studentsms:delete' post.pk %}">Delete</a></td>
        <td><a class="" href="{% url 'studentsms:pdf_id' post.pk %}">Download</a></td>

      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

studentsms/templates/studentsms/pdf_all.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>pdf all records</title>
 
 <style>
     @page{
         size: a4 portrait;
         
     }
     /* table { -pdf-keep-in-frame-mode: overflow;} */
    td, tr{
         border: 1px solid black;     
     }
     th{
        
         padding: 5px;
     }
     table{
         border-collapse: collapse;
         font-size: 12px;
         text-align: left;
     }
     .h{
       font-size: 20px;
     }
</style>
  
</head>
  <body> 
  <div class="h">
  <h1 class="">Esteem Learning Centre, Lokogoma, Abuja</h1>
  <h3>Total Number of Students: {{counter}}</h3>
</div>

  <table class=" table-responsive">
    <thead>
      <tr class="text-left">
        <th scope="col">names</th>
        <th scope="col">class</th>
        <th scope="col">dob</th>
        <th scope="col">admin_no</th>
        <th scope="col">address</th>
        <th scope="col">house</th>
        <th scope="col">status</th>
        
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr style="text-align: center;">
        <td>{{post.names}}</td>
        <td>{{post.level}}</td>
        <td>{{post.dob}}</td>
        <td>{{post.admin_no}}</td>
        <td>{{post.address}}</td>
        <td>{{post.house}}</td>
        <td>{{post.status}}</td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
<!-- second table  -->

<table style="margin-top: 50px;" class=" table1 table-responsive table-bordered">
    <thead>
      <tr>
       
        <th scope="col">father-no</th>
        <th scope="col">father-email</th>
        <th scope="col">mother-no</th>
        <th scope="col">mother-email</th>
        
      </tr>
    </thead>
    <tbody>
        {% for post in myfilter.qs %}
      <tr style="text-align: center;">
        
        <td>{{post.father_no}}</td>
        <td>{{post.father_email|urlize}}</td>
        <td>{{post.mother_no}}</td>
        <td>{{post.mother_email|urlize}}</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>

  </body>
</html>

studentsms/templates/studentsms/pdf_filter.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
-->
    <title>Hello, world!</title>
    <style>
      @page {
          size: a4 portrait;
          margin: 2cm;
      }
  </style>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
-->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

studentsms/templates/studentsms/pdf_id.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>pdf all records</title>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>pdf all records</title>
 
 <style>
     @page{
         size: a4 portrait;
         
     }
     /* table { -pdf-keep-in-frame-mode: overflow;} */
    td, tr{
         border: 1px solid black;     
     }
     th{
        
         padding: 5px;
     }
     table{
         border-collapse: collapse;
         font-size: 12px;
         text-align: left;
     }
     .h{
       font-size: 20px;
     }
</style>
  
</head>
  <body> 
  <div class="h">
  <h1 class="">Esteem Learning Centre, Lokogoma, Abuja</h1>
  <h3>Total Number of Students: {{counter}}</h3>
</div>

  <table class=" table-responsive">
    <thead>
      <tr class="text-left">
        <th scope="col">names</th>
        <th scope="col">class</th>
        <th scope="col">dob</th>
        <th scope="col">admin_no</th>
        <th scope="col">address</th>
        <th scope="col">house</th>
        <th scope="col">status</th>
        
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr style="text-align: center;">
        <td>{{post.names}}</td>
        <td>{{post.level}}</td>
        <td>{{post.dob}}</td>
        <td>{{post.admin_no}}</td>
        <td>{{post.address}}</td>
        <td>{{post.house}}</td>
        <td>{{post.status}}</td>
        
      </tr>
      {% endfor %}
    </tbody>
  </table>
<!-- second table  -->

<table style="margin-top: 50px;" class=" table1 table-responsive table-bordered">
    <thead>
      <tr>
       
        <th scope="col">father-no</th>
        <th scope="col">father-email</th>
        <th scope="col">mother-no</th>
        <th scope="col">mother-email</th>
        
      </tr>
    </thead>
    <tbody>
        {% for post in posts %}
      <tr style="text-align: center;">
        
        <td>{{post.father_no}}</td>
        <td>{{post.father_email|urlize}}</td>
        <td>{{post.mother_no}}</td>
        <td>{{post.mother_email|urlize}}</td>

      </tr>
      {% endfor %}
    </tbody>
  </table>

  </body>
</html>

studentsms/templates/studentsms/update.html
{% extends 'studentsms/base.html' %}

{% load widget_tweaks %}

{% block title %}
<title>Update page</title>
{% endblock %}

{% block body %}
<div class="card-header bg-success text-white" >
<form class="form-control" action="" method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    {% for f in form %}
    <p>{{f.label_tag}}</p>
    <p>{{f|add_class:'form-control'}}</p>
    {% endfor %}
    
   <button type="submit" class="btn  btn-dark">update records</button>
   
</form>
</div>
{% endblock %}